# Generated by Django 4.0.2 on 2022-02-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
